- hosts: selectel
  sudo: yes
  remote_user: root
  roles:
  - { role: nginx, tags: ['nginx'] }
  - { role: percona-mysql, tags: ['mysql']  }
  - { role: memcached, tags: ['memcached']  }
  - { role: php5, tags: ['php']  }
  - { role: wordpress, tags: ['wp']  }
